server {
    listen 8001;
    server_name localhost;

    location = /robots.txt {
        alias /usr/share/nginx/robots.txt;
    }

    location /assets/ {
        alias /usr/share/nginx/assets/;
    }

    location ~ ^/images/-thumb\.(.*)$ {
      alias /usr/share/nginx/images/thumb/$1.jpg;
      default_type image/jpeg;
    }

    location ~ ^/images/(.*)$ {
      alias /usr/share/nginx/images/full/$1.jpg;
      default_type image/jpeg;
    }
}
